#!/usr/bin/env sh
set -eu

cur="$(swaymsg -t get_outputs -r | jq -r '.[] | select(.focused) | .transform')"

case "$cur" in
  normal) next=90 ;;
  90)     next=180 ;;
  180)    next=270 ;;
  270)    next=normal ;;
  *)      next=normal ;; # if flipped/unknown, reset to normal
esac

swaymsg output - transform "$next" >/dev/null
