#!/usr/bin/bash

gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
gsettings set org.gnome.desktop.interface gtk-theme 'Arc-Dark'
kvantummanager --set KvArcDark

ln -sfn /dev/null ~/.config/alacritty/colorscheme
