#!/usr/bin/bash

gsettings set org.gnome.desktop.interface color-scheme 'prefer-light'
kvantummanager --set KvArc

ln -sfn ~/.dotfiles/.config/alacritty/themes/art_kanagawa.toml ~/.config/alacritty/colorscheme
