#!/usr/bin/env bash

ln -sfn ~/.dotfiles/.config/alacritty/themes/art_kanagawa.toml ~/.config/alacritty/colorscheme
ln -sfn /usr/share/foot/themes/paper-color-light ~/.config/foot/colorscheme.ini

gsettings set org.gnome.desktop.interface color-scheme 'prefer-light'
gsettings set org.gnome.desktop.interface gtk-theme 'Arc'
kvantummanager --set KvArc
