[main]
include=~/.config/foot/colorscheme

# electrophoretic
# hacktober
# modus-operandi
# nvim-light
# paper-color-light +
# tempus-dawn
# tempus-past -
# tempus-totus - 
# visibone
# xterm
# zenburn

font=IosevkaTerm Nerd Font:size=16

[key-bindings]
scrollback-up-page=Control+space
scrollback-down-page=Control+BackSpace
