[main]
include=/usr/share/foot/themes/paper-color-light

# electrophoretic
# hacktober
# modus-operandi
# nvim-light
# paper-color-light +
# tempus-dawn
# tempus-past -
# tempus-totus - 
# visibone
# xterm
# zenburn

font=IosevkaTerm Nerd Font:size=16
