[main]
# include=~/.config/foot/colorscheme
include=~/.config/foot/colorscheme.ini

# electrophoretic
# hacktober
# modus-operandi
# nvim-light
# paper-color-light +
# tempus-dawn
# tempus-past -
# tempus-totus - 
# visibone
# xterm
# zenburn
initial-color-theme=light
font=IosevkaTerm Nerd Font:size=16

[key-bindings]
scrollback-up-page=Control+space
scrollback-down-page=Control+BackSpace
