#!/usr/bin/env bash

compile_version=$1
if [[ $target_file == "" ]]; then
    compile_version="${compile_version:-20}"
    echo "Didn't specified compilator version, as argument 1, using default: $compile_version;"
fi

target_file=$2
if [[ $target_file == "" ]]; then
    target_file="main.cpp"
    echo "Didn't specified target file, as argument 2, using default: $target_file;"
fi

build_dir=$3

if [[ $target_file == "" ]]; then
    echo "Didn't specified build directory, as argument 3, using default: main.cpp;"
    g++ -std=c++$compile_version -o $build_dir/$name $target_file
    
fi


name=$4
name="${name:-a.out}"


echo "Compiling with $compile_version, name: $name, build_drir: $build_dir"

g++ -std=c++$compile_version -o $build_dir/$name $target_file

./$build_dir$name

