#!/bin/bash

show_help() {
    echo "Usage:"
    echo "fsg query"
    echo "query - a string to filter in the current folder"
}

query=$1 

if [[ -z "$query" ]]; then 

    ls -a 
    exit 1
fi 

ls -a | grep --color=always -P "$query"


