#!/bin/bash
#

ERROR_TEXT="\e[31m"
INFO_TEXT="\e[32m"
ENDCOLOR="\e[0m"

function create() {

        if [[ -z "$1"  ]]; then 
                echo -e "${ERROR_TEXT}ERROR${ENDCOLOR}: An empty string processed as ticket ID"
                exit 1
        fi

        input="";

        if [[ "$1" =~ ^-* ]]; then
                if [[ "$1" =~ ^--?n$ ]]; then 
                        echo -e "${INFO_TEXT}Extract number${ENDCOLOR}"
                        input="$(echo "$2" | grep -P -o "[\d]+$")"
                fi 
        fi      

        if [[ -z "$input" ]]; then
                input="$1"
        fi      
        
        git worktree add -f ~/repos/PBD_WT/"$input" -b AZ/"$input"
}

create $1 $2
