#!/usr/bin/env bash

printf "%s" "Window name: "
read name

branch_name=$(basename $name)
session_name=$(tmux display-message -p "#S")
clean_name=$(echo $branch_name | tr "./" "__")
target="$session_name:$clean_name"

if ! tmux has-session -t $target 2> /dev/null; then
    tmux neww -dn $clean_name
fi

shift
tmux send-keys -t $target "$*"
