#!/usr/bin/env bash

ln -sfn /dev/null ~/.dotfiles/.config/alacritty/colorscheme

gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
gsettings set org.gnome.desktop.interface gtk-theme 'Arc-Dark'

