#!/usr/bin/env bash

ln -sfn ~/.dotfiles/.config/alacritty/colorscheme.toml ~/.dotfiles/.config/alacritty/colorscheme

gsettings set org.gnome.desktop.interface color-scheme 'prefer-light'
gsettings set org.gnome.desktop.interface gtk-theme 'Arc'
