#!/usr/bin/env bash

ln -sfn ~/.dotfiles/vim/light.vim ~/.vim/colorscheme.vim
ln -sfn ~/.dotfiles/.local/wallpapers/vinyl-light.png ~/.dotfiles/.local/wallpapers/wlp
ln -sfn ~/.config/waybar/style-light.css ~/.config/waybar/style.css

pgrep -x qutebrowser > /dev/null && \
	qutebrowser ':set colors.webpage.darkmode.enabled false' 2>/dev/null || true

gsettings set org.gnome.desktop.interface color-scheme 'prefer-light'
gsettings set org.gnome.desktop.interface gtk-theme 'Arc'

sed -i 's/^initial-color-theme=*/initial-color-theme=light/' ~/.dotfiles/.config/foot/foot.ini 
pkill -u "$USER" -USR2 '^foot(client)?$'

emacsclient --eval '(load-theme (quote modus-operandi) t)' 2>/dev/null || true
