#!/bin/bash

ERROR_TEXT="\e[31m"
INFO_TEXT="\e[32m"
ENDCOLOR="\e[0m"

function extract_number() {
        string=$2
}

function help() {
	echo -e "${INFO_TEXT}Usage${ENDCOLOR}\n	-> -n : extract last digit from the link to form a ticket;\n	${INFO_TEXT}Example:${ENDCOLOR} make_wt -n https://linkwithnumberattheend/4738 => AZ/4738 \n ---------------------"
}

function create() {
        if [[ -z "$1"  ]]; then 
                echo -e "${ERROR_TEXT}ERROR${ENDCOLOR}: An empty string processed as ticket ID"
		help
                exit 1
        fi

        input="";

        if [[ "$1" =~ ^-* ]]; then
                if [[ "$1" =~ ^-?n$ ]]; then 
                        echo -e "${INFO_TEXT}Extract number${ENDCOLOR}"

                        if [[ -z "$2" ]]; then 
                                echo -e "${INFO_TEXT}No input provided${ENDCOLOR}"
				help
                                exit 1
                        fi 

                        input="$(echo "$2" | grep -P -o "[\d]+$")"
                fi 
        fi      

        if [[ -z "$input" ]]; then
                input="$1"
        fi      
        
        git worktree add -f ~/repos/PBD_WT/"$input" -b AZ/"$input"
}

create $1 $2
