#!/bin/bash

archive=$1
app=${archive%%.tar*}
mkdir -v $app
tar xfv $archive -C $app 

cd $app

path_to_file=$(fzf -d .)
echo "Selected file: $path_to_file"
# if the selected file is not a directory
if [ -f $path_to_file ]
then
    folder=$(echo $path_to_file | awk -F/ '{print $(NF-1)}')
    file=${path_to_file##*/}

    rm -rvf ~/Apps/$folder
    cp -vr ./$folder ~/Apps/

    echo "Selected file: $file"
    echo "Selected folder: $folder"

    if [ -f ~/.local/bin/$file ]
    then
        rm -v ~/.local/bin/$file
    fi

    ln -sv ~/Apps/$folder/$file ~/.local/bin/$file
fi

cd ..
