general.import = [
     "~/.config/alacritty/colorscheme",
]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "IosevkaTerm Nerd Font", style = "Regular" }
bold = { family = "IosevkaTerm Nerd Font", style = "SemiBold" }
italic = { family = "IosevkaTerm Nerd Font", style = "SemiBold" }

size = 12

[window]
decorations = "Buttonless"
startup_mode = "SimpleFullscreen"

[selection]
save_to_clipboard = true

